name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    name: Update NuGet package

    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.101

      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@master
        with:
           find: "{{secrets.NUGET_API_KEY_NAME}}"
           replace: "${{ secrets.NUGET_API_KEY_NAME }}"
           include: "nuget.config"
        
      - name: Install nuget
        uses: nuget/setup-nuget@v1
        with:
            nuget-api-key: ${{ secrets.NUGET_API_KEY_NAME }}
            nuget-version: '5.x'
    
      - name: Install dependencies
        run: nuget restore MonoTorrent.sln
        working-directory: ./src

      - name: Build solution and generate NuGet package
        run: dotnet pack -c Release -o out --no-restore
        working-directory: ./src

      - name: Test
        run: dotnet test --no-restore --verbosity normal
        working-directory: ./src

      - name: Push generated package to GitHub registry
        run: nuget push ./src/out/MonoTorrent.1.0.21.nupkg -Source "https://nuget.pkg.github.com/marketly/index.json" -ApiKey ${{ secrets.NUGET_API_KEY_NAME }}
