name: .NET Core

on:
  push:
    branches:
       - '*'         # matches every branch    
  pull_request:
    branches:
       - '*'         # matches every branch    

jobs:
  build:
    runs-on: windows-latest

    name: Build Branch

    steps:

      - name: Hello world action step
        id: hello
        uses: actions/Marketly-Incr-Version@v1.1
        with:
          who-to-greet: 'Mona the Octocat'

      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.101
          source-url: https://nuget.pkg.github.com/marketly/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}      

      - name: Install nuget
        uses: nuget/setup-nuget@v1
        with:
            nuget-api-key: ${{secrets.GITHUB_TOKEN}}
            nuget-version: '5.x'
    
      - name: Set Api Key
        run: nuget setapikey ${{secrets.GITHUB_TOKEN}} -Source "https://nuget.pkg.github.com/marketly/index.json"
    
      - name: Increment version.txt
        id: incr-version
        run: .\incrversion
        shell: pwsh
        working-directory: .

      - name: Set version suffix
        id: version-suffix
        run: .\setsuffix ${{ github.ref }}
        shell: pwsh
        working-directory: .
  
      - name: Install dependencies
        run: nuget restore MonoTorrent.sln
        working-directory: ./src
    
      - name: Build solution and generate NuGet package (master & development branch)
        if: github.ref == 'refs/heads/master' ||  github.ref == 'refs/heads/development'
        run: dotnet pack -c Release -o out --no-restore /property:Version=${{ steps.incr-version.outputs.version }}${{ steps.version-suffix.outputs.versionsuffix }}
        working-directory: ./src

      - name: Build solution and generate NuGet package (feature branch)
        if: github.ref != 'refs/heads/master' &&  github.ref != 'refs/heads/development'
        run: dotnet pack -c Release -o out --no-restore
        working-directory: ./src

      - name: Test
        run: dotnet test --no-restore --verbosity normal
        working-directory: ./src
    
      - name: Commit files
        if: github.ref == 'refs/heads/master' ||  github.ref == 'refs/heads/development'
        run: |
           git config --local user.email "action@github.com"
           git config --local user.name "GitHub Action"
           git commit -m "Increment version number" .\version.txt
        working-directory: .

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
            branch: ${{ github.ref }}
            github_token: ${{secrets.GITHUB_TOKEN}}
        if: github.ref == 'refs/heads/master' ||  github.ref == 'refs/heads/development'

      - name: Push generated package to GitHub registry
        if: github.ref == 'refs/heads/master' ||  github.ref == 'refs/heads/development'
        run: .\pushnuget src\out ${{secrets.GITHUB_TOKEN}}
        shell: pwsh
        working-directory: .
