name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    name: Update NuGet package

    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.101
          source-url: https://nuget.pkg.github.com/marketly/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}      
    
      - name: Build solution and generate NuGet package
        run: dotnet pack -c Release -o out --no-restore
        working-directory: ./src

      - name: Test
        run: dotnet test --no-restore --verbosity normal
        working-directory: ./src

      - name: Push generated package to GitHub registry
        run: dotnet nuget push ./out/*.nupkg --skip-duplicate --Source "https://nuget.pkg.github.com/marketly/index.json" -k ${{secrets.GITHUB_TOKEN}} --no-symbols true
        working-directory: ./src
